language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
  - pip install requests pytest-cov python-dateutil
script:
  - pytest --cov=tenable/tenable_io tests/tenable_io
branches:
  only:
  - master
  - stable