language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
  - | 
    pip install       \
    requests          \
    "pytest>=3.6"     \
    pytest-cov        \
    pytest-datafiles  \
    python-dateutil   \
    lxml
script:
  - pytest --cov=tenable tests/io tests/reports
branches:
  only:
  - master
  - stable